const PARTNERS_DATA= [
  {
    "image1":"assets/partners/technopark.png",
    "image2":"assets/partners/lastartupstation.png"
  },
  {
    "image1":"assets/partners/hackpitch.png",
    "image2":"assets/partners/mdi.png"
  },
  {
    "image1":"assets/partners/ahk.png",
    "image2":"assets/partners/BELGO.png"
  },
  {
    "image1":"assets/partners/cicp2.png",
    "image2":"assets/partners/aujourdhui.png"
  },
  {
    "image1":"assets/partners/diplomatique.png",
    "image2":"assets/partners/telecontact.png"
  },
  {
    "image1":"assets/partners/kompass.png",
    "image2":"assets/partners/lebrif.png"
  },
  {
    "image1":"assets/partners/infomediaire.png",
    "image2":"assets/partners/lastory.png"
  },
  {
    "image1":"assets/partners/lodjmedia.png",
    "image2":"assets/partners/course.png"
  },
  {
    "image1":"assets/partners/buzzevents.png",
    "image2":"assets/partners/mfcontent.png"
  },
  {
    "image1":"assets/partners/itskils.png",
    "image2":"1"
  },
];

