const PARTNERS_DATA= [
  {
    "image1":"assets/partners/ahkxc.png",
    "image2":"assets/partners/lastartupstation.png"
  },
  {
    "image1":"assets/partners/.png",
    "image2":"assets/partners/mdi.png"
  },
  {
    "image1":"assets/partners/ahk.png",
    "image2":"assets/partners/.png"
  },
  {
    "image1":"assets/partners/.png",
    "image2":"assets/partners/.png"
  },
  {
    "image1":"assets/partners/.png",
    "image2":"assets/partners/.png"
  },
  {
    "image1":"assets/partners/.png",
    "image2":"assets/partners/lebrif.png"
  },
  {
    "image1":"assets/partners/infomediaire.png",
    "image2":"assets/partners/lastory.png"
  },
  {
    "image1":"assets/partners/lodjmedia.png",
    "image2":"assets/partners/course.png"
  },
  {
    "image1":"assets/partners/buzzevents.png",
    "image2":"assets/partners/mfcontent.png"
  },
  {
    "image1":"assets/partners/itskils.png",
    "image2":"1"
  },
  {
    "image1":"assets/partners/itskils.png",
    "image2":"1"
  },
];

