const PARTNERS_DATA= [
  {
    "image1":"assets/partners/technopark.png",
    "image2":"assets/partners/ammc.png"
  },
  {
    "image1":"assets/partners/cicp.png",
    "image2":"assets/partners/lastartupstation.png"
  },
  {
    "image1":"assets/partners/nortis.png",
    "image2":"assets/partners/okysolutions.png"
  },
  {
    "image1":"assets/partners/buzzevents.png",
    "image2":"assets/partners/tdm.png"
  },
  {
    "image1":"assets/partners/es2im.png",
    "image2":"assets/partners/ahk.png"
  },
  {
    "image1":"assets/partners/diplomatique.png",
    "image2":"assets/partners/telecontact.png"
  },
  {
    "image1":"assets/partners/kerixnet.png",
    "image2":"assets/partners/kompass.png"
  },
  {
    "image1":"assets/partners/infomediaire.png",
    "image2":"assets/partners/aujourdhui.png"
  },
  {
    "image1":"assets/partners/industrie-du-maroc.png",
    "image2":"assets/partners/lebrief.png"
  }, {
    "image1":"assets/partners/media7.png",
    "image2":"assets/partners/conso-news.png"
  }, {
    "image1":"assets/partners/hitradio.png",
    "image2":"assets/partners/medi1tv.png"
  },
  {
    "image1":"assets/partners/medi1radio.png",
    "image2":"assets/partners/BELGO.png"
  },
  {
    "image1":"assets/partners/lastory.png",
    "image2":"assets/partners/course.png"
  },
];

